function EZ = EZ_m2_s0_3_5(dt,Dm0,Dm1,Dm2,Ds0)
%EZ_m2_s0_3_5
%    EZ = EZ_m2_s0_3_5(DT,Dm0,Dm1,Dm2,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-May-2025 08:49:29

%E(Z) function of refined Hermite, J=3  K=5 ndiff_mu = 2, ndiff_sigma = 0
t2 = Dm0.^2;
t3 = Dm0.^3;
t4 = Dm1.^2;
t5 = Dm1.^3;
t6 = Dm2.^2;
t8 = Ds0.^2;
t9 = dt.^2;
t10 = dt.^3;
t12 = sqrt(dt);
t7 = t4.^2;
t11 = t9.^2;
t13 = t12.^3;
t14 = t12.^5;
t15 = t12.^7;
t16 = t13.^3;
mt1 = [(t8.*(Dm2.*t13.*1.2e+2+Dm1.*Dm2.*t14.*1.2e+2+Dm0.*t6.*t15.*7.0e+1+Dm2.*t4.*t15.*7.0e+1+Dm2.*t5.*t16.*3.0e+1+Dm2.^3.*t8.*t16.*2.1e+1+Dm0.*Dm1.*t6.*t16.*1.02e+2)+Dm0.*t12.*4.8e+2+Dm0.*Dm1.*t13.*2.4e+2+Dm0.*t4.*t14.*8.0e+1+Dm2.*t2.*t14.*8.0e+1+Dm0.*t5.*t15.*2.0e+1+Dm0.*t7.*t16.*4.0+t3.*t6.*t16.*1.6e+1+Dm1.*Dm2.*t2.*t15.*8.0e+1+Dm2.*t2.*t4.*t16.*4.4e+1)./(Ds0.*4.8e+2)];
mt2 = [(dt.*t2.*2.4e+2+t8.*(t8.*(t6.*t10.*1.05e+2+Dm1.*t6.*t11.*2.22e+2)+Dm1.*dt.*2.4e+2+t4.*t9.*1.6e+2+t5.*t10.*8.0e+1+t7.*t11.*3.2e+1+Dm0.*Dm2.*t9.*2.8e+2+t2.*t6.*t11.*1.7e+2+Dm0.*Dm1.*Dm2.*t10.*4.4e+2+Dm0.*Dm2.*t4.*t11.*3.82e+2+2.4e+2)+Dm1.*t2.*t9.*2.4e+2+Dm2.*t3.*t10.*8.0e+1+t2.*t4.*t10.*1.4e+2+t2.*t5.*t11.*6.0e+1+Dm1.*Dm2.*t3.*t11.*1.2e+2)./(t8.*2.4e+2)];
mt3 = [(1.0./Ds0.^3.*(t3.*t13.*8.0e+1+t8.*(Dm0.*t12.*2.4e+2+t8.*(Dm2.*t13.*1.4e+2+Dm1.*Dm2.*t14.*3.0e+2+Dm0.*t6.*t15.*2.92e+2+Dm2.*t4.*t15.*3.55e+2)+Dm0.*Dm1.*t13.*3.6e+2+Dm0.*t4.*t14.*3.2e+2+Dm2.*t2.*t14.*2.6e+2+Dm0.*t5.*t15.*2.1e+2+Dm1.*Dm2.*t2.*t15.*5.4e+2)+Dm1.*t3.*t14.*1.2e+2+t3.*t4.*t15.*1.0e+2+Dm2.*t2.^2.*t15.*4.0e+1))./8.0e+1];
EZ = [mt1;mt2;mt3];
end
