function EZ = EZ_m0_s0_3_12(dt,Dm0,Ds0)
%EZ_m0_s0_3_12
%    EZ = EZ_m0_s0_3_12(DT,Dm0,Ds0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    05-May-2025 16:29:53

%E(Z) function of refined Hermite, J=3  K=12 ndiff_mu = 0, ndiff_sigma = 0
t2 = Ds0.^2;
t3 = sqrt(dt);
EZ = [(Dm0.*t3)./Ds0;(t2+Dm0.^2.*dt)./t2;1.0./Ds0.^3.*(Dm0.^3.*t3.^3+Dm0.*t2.*t3.*3.0)];
end
