function g_ll = g_LL(x0,x,dt,par1,par2,par3,par4,par5)
%g_LL
%    G_LL = g_LL(X0,X,DT,PAR1,PAR2,PAR3,PAR4,PAR5)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    09-Jul-2025 17:59:32

%Gradient vector of log-likelihood for Euler reconstruction
%based on the following drift and diffusion functions:
%   mu=@(x,par)par(1).*((x-m)./s).^3+par(2).*((x-m)./s).^2+par(3).*(x-m)./s+par(4)
%   sigma=@(x,par)par(5)
t2 = 1.0./par5.^2;
t3 = -x;
t4 = x0-3.467262592587762;
t5 = x0.*5.818623040847281e-1;
t6 = t5-2.017469400989903;
t7 = par3.*t4.*5.818623040847281e-1;
t8 = t6.^2;
t9 = t6.^3;
t10 = par1.*t9;
t11 = par2.*t8;
t12 = par4+t7+t10+t11;
t13 = dt.*t12;
t14 = t3+t13+x0;
g_ll = [-t2.*t9.*t14;-t2.*t8.*t14;-t2.*t6.*t14;-t2.*t14;-1.0./par5+(1.0./par5.^3.*t14.^2)./dt];
end
